### ISSUE TITLE
Cannot retrieve SMS on device

### ISSUE THREAD

**Issue by MichelleLum168** [faizalshap/react-native-otp-verify#89]
Some devices (e.g. Samsung A32) when updated to the latest firmware have not been able to retrieve the sms. 
Below are the logs with the error when trying to retrieve the sms.

OtpVerifyModule: Could not start sms listener
    com.google.android.gms.common.api.ApiException: 17: Device doesn't support the messaging feature
        at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@18.0.1:4)
        at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@18.0.1:1)
        at com.google.android.gms.internal.auth-api-phone.zzz.zzb(com.google.android.gms:play-services-auth-api-phone@@17.5.1:1)
        at com.google.android.gms.internal.auth-api-phone.zzi.zza(com.google.android.gms:play-services-auth-api-phone@@17.5.1:2)
        at com.google.android.gms.internal.auth-api-phone.zzb.onTransact(com.google.android.gms:play-services-auth-api-phone@@17.5.1:3)
        at android.os.Binder.execTransactInternal(Binder.java:1321)
        at android.os.Binder.execTransact(Binder.java:1280)

This is working on many other devices on the latest firmware too.

**Comment by vedantgilhotra** [comment]
Facing the same issue

**Comment by khethelogp** [comment]
I have the same problem, I've recently upgraded to android 13

and I get `[Error: 17: Device doesn't support the messaging feature]`

**Comment by EvertV** [comment]
Seems to be a general issue, not related to this package. See https://issuetracker.google.com/issues/275036593

**Comment by Ranjithramesh67** [comment]
Hi Guys, try this library [react-native-sms-receiver](https://www.npmjs.com/package/react-native-sms-receiver) to read the received message.

**Comment by samih-dev** [comment]
anyone has updates on this maybe ?

**Comment by aarie33** [comment]
I still face the issue on version 1.1.6
