### ISSUE TITLE
app is getting crashed after getting otp

### ISSUE THREAD

**Issue by roshanj655** [faizalshap/react-native-otp-verify#91]
My app is getting closed after read sms, I got the otp in console then app crashed

**Comment by umairalirehan** [comment]
Also getting same issue

**Comment by faizalshap** [comment]
Please add Logs

**Comment by neoshaikhimran** [comment]
I am also facing same issue

**Comment by neoshaikhimran** [comment]
@faizalshap please update

**Comment by neoshaikhimran** [comment]
remove this set of code from Android.xml

**Comment by neoshaikhimran** [comment]
remove this set of code from Android.xml it work"s for me

**Comment by neoshaikhimran** [comment]
this set of code to

**Comment by ealimardaniii** [comment]
> Please add Logs

 FATAL EXCEPTION: main
                                                                                                    Process: com.carreta, PID: 6869
                                                                                                    java.lang.RuntimeException: Unable to start receiver com.reactnativeotpautofill.OtpBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
                                                                                                    	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4458)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2256)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
                                                                                                    	at com.reactnativeotpautofill.OtpBroadcastReceiver.onReceive(OtpBroadcastReceiver.java:39)
                                                                                                    	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4449)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2256) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
2023-12-12 02:46:39.258  6869-6869  Process                 com.carreta                          I  Sending signal. PID: 6869 SIG: 9
