### ISSUE TITLE
Runtime Exception on some devices

### ISSUE THREAD

**Issue by AndreiBehel** [faizalshap/react-native-otp-verify#94]
We have observered several exceptions on some devices on production.
Here is stack trace:
<details>
<summary>Huawei Enjoy 9s Android 8.1.0</summary>
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
    at com.faizal.OtpVerify.OtpBroadcastReceiver.onReceive(OtpBroadcastReceiver.java:49)
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52560(LoadedApk.java:1316)
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6536)
    at java.lang.reflect.Method.invokeImpl(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:411)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x400010 pkg=com.bigwallet.app } in com.faizal.OtpVerify.OtpBroadcastReceiver@c342b23
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52560(LoadedApk.java:1326)
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6536)
    at java.lang.reflect.Method.invokeImpl(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:411)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)
</details>

<details>
<summary>Samsung Galaxy A70 Android 8.1.0</summary>
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
    at com.faizal.OtpVerify.OtpBroadcastReceiver.onReceive(OtpBroadcastReceiver.java:49)
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52560(LoadedApk.java:1316)
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6536)
    at java.lang.reflect.Method.invokeImpl(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:411)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x400010 pkg=com.bigwallet.app } in com.faizal.OtpVerify.OtpBroadcastReceiver@dd681ce
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52560(LoadedApk.java:1326)
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7
    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6536)
    at java.lang.reflect.Method.invokeImpl(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:411)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)
</details>

**Comment by rajdhakate** [comment]
Facing the same issue. On Samsung A70

Possibly the Bundle object is null in certain scenarios (`OtpBroadcastReceiver > line 49`)
a `null` check should fix it probably @faizalshap

**Comment by raviraj-tudip** [comment]
Facing the same issue from some days on some older device. Please provide some solutions to us.

Issue:
Fatal Exception: java.lang.RuntimeException
Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x400010 pkg=com.packagename } in com.faizal.OtpVerify.d@75ee2b7

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference

Device: **Vivo**
OS: Android **8.1.0**

**Comment by MursiDirect** [comment]
facing the same issue
any solution for this issue, please? @faizalshap

**Comment by hariprakashhvk** [comment]
Facing the same issue on Motorola One vision
O.S: Android 8.1.0

**Comment by opayen** [comment]
Fixed by #97
